# Generated by Django 4.2.6 on 2023-10-09 13:16

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutphoto', models.ImageField(blank=True, upload_to='about/profile')),
                ('aboutheadline', models.CharField(max_length=150)),
                ('aboutdetail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='aboutproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=150)),
                ('num', models.IntegerField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('detail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_date', models.CharField(blank=True, max_length=150)),
                ('education_name', models.CharField(blank=True, max_length=150)),
                ('education_detail', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_detail', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='first_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstimage', models.ImageField(blank=True, upload_to='profile')),
                ('displayname', models.CharField(max_length=150)),
                ('nametitle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='My_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skillsdetail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='My_Skills1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MySkills', models.CharField(blank=True, max_length=150)),
                ('percent', models.CharField(blank=True, max_length=150)),
                ('width_percent', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='My_Skills2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MySkills', models.CharField(blank=True, max_length=150)),
                ('percent', models.CharField(blank=True, max_length=150)),
                ('width_percent', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicespng', models.CharField(blank=True, max_length=150)),
                ('Services_name', models.CharField(blank=True, max_length=150)),
                ('Services_detail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfoliodetail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Category_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resumedetail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_detail', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category', unique=True)),
                ('Portfolio', models.ImageField(upload_to='Services/png')),
                ('Services_name', models.CharField(blank=True, max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfoliocategory')),
            ],
        ),
    ]
